---
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'build/**'
      - 'doc/**'
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'build/**'
      - 'doc/**'
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2

      - id: cache-ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: linux

      - name: Install dependencies
        run: |
          sudo apt install -y --no-install-recommends \
            meson \
            check

      - name: Full Build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          directory: output/full
          setup-options: -Ddocumentation=false -Dtest=true
          options: --verbose

      - name: Mini Build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          directory: output/mini
          setup-options: -Ddocumentation=false -Dtest=true -Dtcp=false
          options: --verbose

  build-macos:
    runs-on: macos-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2

      - id: cache-ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: macos

      - uses: actions/setup-python@v1

      - name: Install dependencies
        run: |
          brew install \
            meson ninja \
            check

      - name: Meson Build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          directory: output
          setup-options: -Ddocumentation=false -Dtest=true
          options: --verbose

  build-windows:
    runs-on: windows-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2

      - name: Meson Build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          directory: output
          setup-options: -Ddocumentation=false -Dtest=true
          options: --verbose
          meson-version: 1.3.0

  build-windows-msvc:
    runs-on: windows-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2

      - name: Add VisualStudio command line tools into path
        uses: ilammy/msvc-dev-cmd@v1

      - name: Meson Build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          directory: output
          setup-options: -Ddocumentation=false -Dtest=true
          options: --verbose
          meson-version: 1.3.0
  build-msys2:
    strategy:
      matrix:
        platform: ['MINGW64', 'UCRT64']
    defaults:
      run:
        shell: msys2 {0}
    runs-on: windows-latest
    steps:
      - id: checkout
        uses: actions/checkout@v4

      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.platform}}
          pacboy: >-
            cc:p
            check:p
            meson:p
            ninja:p

      - name: Compile and Test
        run: |
          meson setup "${{github.workspace}}/build" -Dtest=true -Dwarning_level=3
          meson compile -C "${{github.workspace}}/build" --verbose
          meson test -C "${{github.workspace}}/build" --verbose
